// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThiThuToiec2.Models;

namespace ThiThuToiec2.Migrations
{
    [DbContext(typeof(ThiThuToiec2Context))]
    [Migration("20190825063054_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThiThuToiec2.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("Sdt");

                    b.Property<string>("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DAA");

                    b.Property<string>("DAB");

                    b.Property<string>("DAC");

                    b.Property<string>("DAD");

                    b.Property<string>("DADung");

                    b.Property<int>("DoanVanAudioImageID");

                    b.Property<string>("NumBer");

                    b.Property<string>("cauHoi");

                    b.HasKey("Id");

                    b.HasIndex("DoanVanAudioImageID");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.CauTraLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DAChon");

                    b.Property<int>("IdCauHoi");

                    b.Property<int>("LichSuNguoiDungID");

                    b.Property<string>("PartName");

                    b.HasKey("Id");

                    b.HasIndex("LichSuNguoiDungID");

                    b.ToTable("CauTraLois");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.DoanVanAudioImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Audio");

                    b.Property<string>("DoanVan");

                    b.Property<string>("Image");

                    b.Property<string>("PartID");

                    b.HasKey("ID");

                    b.ToTable("DoanVanAudioImages");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.LichSuNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Diem");

                    b.Property<int>("TestID");

                    b.Property<int>("TienDoNguoiDungID");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.HasIndex("TienDoNguoiDungID");

                    b.ToTable("LichSuNguoiDungs");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.Part", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PartName");

                    b.Property<int>("TestID");

                    b.HasKey("ID");

                    b.HasIndex("TestID");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TestName");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.TienDoNguoiDung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<int>("thangDiem");

                    b.HasKey("ID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("TienDoNguoiDungs");
                });

            modelBuilder.Entity("ThiThuToiec2.Models.CauHoi", b =>
                {
                    b.HasOne("ThiThuToiec2.Models.DoanVanAudioImage")
                        .WithMany("cauHoi")
                        .HasForeignKey("DoanVanAudioImageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThiThuToiec2.Models.CauTraLoi", b =>
                {
                    b.HasOne("ThiThuToiec2.Models.LichSuNguoiDung")
                        .WithMany("CauTraLoi")
                        .HasForeignKey("LichSuNguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThiThuToiec2.Models.LichSuNguoiDung", b =>
                {
                    b.HasOne("ThiThuToiec2.Models.TienDoNguoiDung")
                        .WithMany("lichSuNguoiDung")
                        .HasForeignKey("TienDoNguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThiThuToiec2.Models.Part", b =>
                {
                    b.HasOne("ThiThuToiec2.Models.Test")
                        .WithMany("part")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThiThuToiec2.Models.TienDoNguoiDung", b =>
                {
                    b.HasOne("ThiThuToiec2.Models.Account")
                        .WithOne("tienDoNguoiDung")
                        .HasForeignKey("ThiThuToiec2.Models.TienDoNguoiDung", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
